import type {Metadata} from "next";
import {Raleway} from "next/font/google";
import "./globals.css";
import Navbar from "@/component/navbar/navbar";
import Footer from "@/component/footer";

const raleway = Raleway({
    variable: "--font-raleway",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${raleway.variable} antialiased`}
        >
        <Navbar/>
        <main className="bg-gray-50 min-h-screen">{children}</main>
        <Footer/>
        </body>
        </html>
    );
}
